return {
  {
    type = 'win',
    title = 'Go - Collect 200 as you pass',
    price = 200,
    card_image = 'go',
  },
  {
    type = 'property',
    title_html = '<N>Vanilla Avenue',
    title = 'Vanilla Avenue',
    price = 60,
    rent = 2,
    house = 10,
    house2 = 30,
    house3 = 90,
    house4 = 160,
    hotel = 250,
    house_hotel = 50,
    mortgage = 30,
    header_color = '590c38',
  },
  {
    type = 'chest',
    title = 'Community Chest',
    price = 0,
    card_image = 'community2',
  },
  {
    type = 'property',
    title_html = '<N>Defilante Street',
    title = 'Defilante Street',
    price = 60,
    rent = 4,
    house = 20,
    house2 = 60,
    house3 = 180,
    house4 = 320,
    hotel = 450,
    house_hotel = 50,
    mortgage = 30,
    header_color = '590c38',
  },
  {
    type = 'lose',
    title = 'Income Tax',
    price = 200,
    mortgage = 100,
    card_image = 'income_tax',
  },
  {
    type = 'station',
    title = 'Deathmatch Station',
    price = 200,
    mortgage = 100,
    header_color = 0,
    card_image = 'train',
  },
  {
    type = 'property',
    title = 'Parkour Street',
    price = 100,
    rent = 6,
    house = 30,
    house2 = 90,
    house3 = 270,
    house4 = 400,
    hotel = 550,
    house_hotel = 50,
    mortgage = 50,
    header_color = '87a5d6',
  },
  {
    type = 'chance',
    title = 'Chance',
    price = 0,
    card_image = 'chance2',
  },
  {
    type = 'property',
    title = 'Racing Route',
    price = 100,
    rent = 6,
    house = 30,
    house2 = 90,
    house3 = 270,
    house4 = 400,
    hotel = 550,
    house_hotel = 50,
    mortgage = 50,
    header_color = '87a5d6',
  },
  {
    type = 'property',
    title = 'Fight Boulevard',
    price = 120,
    rent = 8,
    house = 40,
    house2 = 100,
    house3 = 300,
    house4 = 450,
    hotel = 600,
    house_hotel = 50,
    mortgage = 60,
    header_color = '87a5d6',
  },
  {
    type = 'jailvisit',
    title = 'In Jail - Just Visiting',
    price = 0,
    card_image = 'jail',
  },
  {
    type = 'property',
    title_html = '<font size="10">Transformice Alley',
    title = 'Transformice Alley',
    price = 140,
    rent = 10,
    house = 50,
    house2 = 150,
    house3 = 450,
    house4 = 625,
    hotel = 750,
    house_hotel = 100,
    mortgage = 70,
    header_color = 'ee3878',
  },
  {
    type = 'utility',
    title = 'Electric Utility Company',
    price = 150,
    mortgage = 75,
    header_color = 0,
    card_image = 'electric',
  },
  {
    type = 'property',
    title = 'Batata Avenue',
    price = 140,
    rent = 10,
    house = 50,
    house2 = 150,
    house3 = 450,
    house4 = 625,
    hotel = 750,
    house_hotel = 100,
    mortgage = 70,
    header_color = 'ee3878',
  },
  {
    type = 'property',
    title = 'Dancefloor Alley',
    price = 160,
    rent = 12,
    house = 60,
    house2 = 180,
    house3 = 500,
    house4 = 700,
    hotel = 900,
    house_hotel = 100,
    mortgage = 80,
    header_color = 'ee3878',
  },
  {
    type = 'station',
    title = 'Trade Station',
    price = 200,
    mortgage = 100,
    header_color = 0,
    card_image = 'train',
  },
  {
    type = 'property',
    title_html = '<font size="12">Prophunt Avenue',
    title = 'Prophunt Avenue',
    price = 180,
    rent = 14,
    house = 70,
    house2 = 200,
    house3 = 550,
    house4 = 750,
    hotel = 950,
    house_hotel = 100,
    mortgage = 90,
    header_color = 'f57f23',
  },
  {
    type = 'chest',
    title = 'Community Chest',
    price = 0,
    card_image = 'community2',
  },
  {
    type = 'property',
    title = 'Football Venue',
    price = 180,
    rent = 14,
    house = 70,
    house2 = 200,
    house3 = 550,
    house4 = 750,
    hotel = 950,
    house_hotel = 100,
    mortgage = 90,
    header_color = 'f57f23',
  },
  {
    type = 'property',
    title = 'Unotfm Street',
    price = 200,
    rent = 16,
    house = 80,
    house2 = 220,
    house3 = 600,
    house4 = 800,
    hotel = 1000,
    house_hotel = 100,
    mortgage = 100,
    header_color = 'f57f23',
  },
  {
    type = 'empty',
    title = 'Village AFK',
    price = 0,
    card_image = 'afkvillage',
  },
  {
    type = 'property',
    title = 'Spiritual Avenue',
    price = 220,
    rent = 18,
    house = 90,
    house2 = 250,
    house3 = 700,
    house4 = 875,
    hotel = 1050,
    house_hotel = 150,
    mortgage = 110,
    header_color = 'ef3a24',
  },
  {
    type = 'chance',
    title = 'Chance',
    price = 0,
    card_image = 'chance2',
  },
  {
    type = 'property',
    title = 'Freezertag Road',
    price = 220,
    rent = 18,
    house = 90,
    house2 = 250,
    house3 = 700,
    house4 = 875,
    hotel = 1050,
    house_hotel = 150,
    mortgage = 110,
    header_color = 'ef3a24',
  },
  {
    type = 'property',
    title_html = '<font size="10">Towerdefense Street',
    title = 'Towerdefense Street',
    price = 240,
    rent = 20,
    house = 100,
    house2 = 300,
    house3 = 750,
    house4 = 925,
    hotel = 1100,
    house_hotel = 150,
    mortgage = 120,
    header_color = 'ef3a24',
  },
  {
    type = 'station',
    title = 'Survivor Station',
    price = 200,
    mortgage = 100,
    header_color = 0,
    card_image = 'train',
  },
  {
    type = 'property',
    title = 'Circuit Avenue',
    price = 260,
    rent = 22,
    house = 110,
    house2 = 330,
    house3 = 800,
    house4 = 975,
    hotel = 1150,
    house_hotel = 150,
    mortgage = 130,
    header_color = 'fde703',
  },
  {
    type = 'property',
    title = 'Ratapult Plaza',
    price = 260,
    rent = 22,
    house = 110,
    house2 = 330,
    house3 = 800,
    house4 = 975,
    hotel = 1150,
    house_hotel = 150,
    mortgage = 130,
    header_color = 'fde703',
  },
  {
    type = 'utility',
    title = 'Water Cbase Company',
    price = 150,
    mortgage = 75,
    header_color = 0,
    card_image = 'water',
  },
  {
    type = 'property',
    title = 'Mycity Avenue',
    price = 280,
    rent = 24,
    house = 120,
    house2 = 360,
    house3 = 850,
    house4 = 1025,
    hotel = 1200,
    house_hotel = 150,
    mortgage = 140,
    header_color = 'fde703',
  },
  {
    type = 'jail',
    title = 'Go To Jail',
    price = 0,
    card_image = 'gojail',
  },
  {
    type = 'property',
    title_html = '<font size="12">Hardcamp Avenue',
    title = 'Hardcamp Avenue',
    price = 300,
    rent = 26,
    house = 130,
    house2 = 390,
    house3 = 900,
    house4 = 1100,
    hotel = 1275,
    house_hotel = 200,
    mortgage = 150,
    header_color = '13a55b',
  },
  {
    type = 'property',
    title_html = '<font size="10">Hidenseek Boulevard',
    title = 'Hidenseek Boulevard',
    price = 300,
    rent = 26,
    house = 130,
    house2 = 390,
    house3 = 900,
    house4 = 1100,
    hotel = 1275,
    house_hotel = 200,
    mortgage = 150,
    header_color = '13a55b',
  },
  {
    type = 'chest',
    title = 'Community Chest',
    price = 0,
    card_image = 'community2',
  },
  {
    type = 'property',
    title = 'Divinity Avenue',
    price = 320,
    rent = 28,
    house = 150,
    house2 = 450,
    house3 = 1000,
    house4 = 1200,
    hotel = 1400,
    house_hotel = 200,
    mortgage = 160,
    header_color = '13a55b',
  },
  {
    type = 'station',
    title = 'Cannonup Station',
    price = 200,
    mortgage = 100,
    header_color = 0,
    card_image = 'train',
  },
  {
    type = 'chance',
    title = 'Chance',
    price = 0,
    card_image = 'chance2',
  },
  {
    type = 'property',
    title_html = '<N>Records Plaza',
    title = 'Records Plaza',
    price = 350,
    rent = 35,
    house = 175,
    house2 = 500,
    house3 = 1100,
    house4 = 1300,
    hotel = 1500,
    house_hotel = 200,
    mortgage = 175,
    header_color = '274ea1',
  },
  {
    type = 'lose',
    title = 'Luxury Tax',
    price = 100,
    card_image = 'luxury_tax',
  },
  {
    type = 'property',
    title_html = '<N><font size="12">Bootcamp Avenue',
    title = 'Bootcamp Avenue',
    price = 400,
    rent = 50,
    house = 200,
    house2 = 600,
    house3 = 1400,
    house4 = 1700,
    hotel = 2000,
    house_hotel = 200,
    mortgage = 200,
    header_color = '274ea1',
  },
}